; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.26"

; Modules
projects[active_tags][version] = "2.x-dev"

projects[ajax_comments][version] = "1.0-alpha1"

projects[auto_nodetitle][version] = "1.0"

projects[best_answer][subdir] = "custom/features"
projects[best_answer][version] = "3.0"

projects[better_exposed_filters][version] = "3.0-beta3"

projects[boxes][version] = "1.1"

projects[ctools][version] = "1.2"

projects[cck_blocks][version] = "1.1"

projects[chosen][version] = "1.0"

projects[context][version] = "3.0-beta7"

projects[context_og][subdir] = "custom"
projects[context_og][version] = "2.1"

projects[date][version] = "2.6"

projects[devel][version] = "1.3"

projects[diff][version] = "3.2"

projects[relation][version] = "1.x-dev"

projects[emphasis][version] = "1.0"

projects[entity][version] = "1.2"

projects[entitycache][version] = "1.1"

projects[entityreference][version] = "1.0-rc1"

projects[entityreference_prepopulate][version] = "1.3"

projects[eva][subdir] = "custom"
projects[eva][version] = "1.2"

projects[features_extra][version] = "1.0-beta1"

projects[features][version] = "2.0-rc3"

projects[feeds][subdir] = "custom"
projects[feeds][version] = "2.0-alpha8"

projects[feeds_crawler][subdir] = "custom"
projects[feeds_crawler][version] = "1.0-beta2"
projects[feeds_crawler][patch][] = "https://drupal.org/files/issues/feeds_crawler-404fix-2189555-1.patch"

projects[fences][version] = "1.0"

projects[field_collection][version] = "1.0-beta5"

projects[field_group][version] = "1.1"

projects[field_permissions][version] = "1.0-beta2"

projects[flag][version] = "2.0-beta9"

projects[i18n][version] = "1.10"

projects[insert][version] = "1.3"

projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_update][version] = "2.3"

projects[libraries][version] = "2.1"

projects[mail_edit][version] = "1.0"

projects[markdown][subdir] = "custom"
projects[markdown][version] = "1.0"

projects[mediaelement][subdir] = "custom"
projects[mediaelement][version] = "1.2"

projects[messaging][version] = "1.0-alpha2"

projects[metatag][version] = "1.0-beta7"

projects[migrate][subdir] = "custom"
projects[migrate][version] = "2.5"

projects[module_filter][version] = "1.7"

projects[references][version] = "2.0"

projects[nodereference_count][version] = "1.0"

projects[nodereference_url][version] = "1.12"

projects[notifications][subdir] = "custom"
projects[notifications][version] = "1.0-alpha2"

projects[og][version] = "2.5"

projects[og_extras][version] = "1.1"

projects[pathauto][version] = "1.2"

projects[profile2][version] = "1.3"

projects[progress][version] = "1.4"

projects[redirect][version] = "1.x-dev"

projects[services][version] = "3.5"

projects[rules][version] = "2.3"

projects[stringoverrides][version] = "1.8"

projects[strongarm][version] = "2.0"

projects[subscriptions][version] = "1.1"

projects[token][version] = "1.5"

projects[transliteration][version] = "3.1"

projects[ultimate_cron][version] = "1.9"

projects[user_badges][version] = "3.x-dev"

projects[userpoints][version] = "1.0"

projects[variable][version] = "2.3"

projects[views][version] = "3.7"

projects[views_data_export][version] = "3.0-beta6"

projects[voting_rules][version] = "1.0-alpha1"

projects[votingapi][version] = "2.11"

projects[workbench][version] = "1.2"

projects[workbench_moderation][version] = "1.3"

